version: '3'

services:

  zoo-1:
    hostname: zoo-1
    restart: always
    image: nickkbright/zoo1:latest
    networks:
      vnet:
        aliases: 
          - zoo-1
  
  zoo-2:
    hostname: zoo-2
    restart: always
    image: nickkbright/zoo2:latest
    networks: 
      vnet:
        aliases: 
          - zoo-2
  
  zoo-3:
    hostname: zoo-3
    restart: always
    image: nickkbright/zoo3:latest
    networks: 
      vnet:
        aliases: 
          - zoo-3
  
  hdfs:
    image: nickkbright/hdfs:latest
    ports:
        - 8088:8088
    networks: 
      vnet:
        aliases: 
          - hdfs

  drill-1:
    hostname: drill-1
    image: nickkbright/apache-drill:1-14
    ports:
      - 8047:8047
    depends_on:
      - "zoo-1"
      - "zoo-2"
      - "zoo-3"
      - "hdfs"
    networks: 
      vnet:
        aliases: 
          - drill-1
    healthcheck:
      test: ["CMD", "curl", "-f", "drill-1:8047"]
      interval: 20s
      timeout: 3s
      retries: 10

  drill-2:
    hostname: drill-2
    image: nickkbright/apache-drill:1-14
    depends_on:
      - "zoo-1"
      - "zoo-2"
      - "zoo-3"
      - "hdfs"
    networks: 
      vnet:
        aliases: 
          - drill-2
    healthcheck:
      test: ["CMD", "curl", "-f", "drill-2:8047"]
      interval: 20s
      timeout: 3s
      retries: 10

  
  drill-3:
    hostname: drill-3
    image: nickkbright/apache-drill:1-14
    depends_on:
      - "zoo-1"
      - "zoo-2"
      - "zoo-3"
      - "hdfs"
    networks: 
      vnet:
        aliases: 
          - drill-3
    healthcheck:
      test: ["CMD", "curl", "-f", "drill-3:8047"]
      interval: 20s
      timeout: 3s
      retries: 10

  
  drill-4:
    hostname: drill-4
    image: nickkbright/apache-drill:1-14
    depends_on:
      - "zoo-1"
      - "zoo-2"
      - "zoo-3"
      - "hdfs"
    networks: 
      vnet:
        aliases: 
          - drill-4
    healthcheck:
      test: ["CMD", "curl", "-f", "drill-4:8047"]
      interval: 20s
      timeout: 3s
      retries: 10

networks: 
  vnet:
    driver: bridge    
