version: '3'

services:

  zoo-1:
    build:
      context: ./zookeeper
      args:
        quorum: 'server.1=0.0.0.0:2888:3888'
        server_num: '1'
    ports:
      - 2181:2181
    networks: ["vnet"]
  
  hdfs:
    build:
      context: ./hadoop
    ports:
        - 8088:8088
    networks: ["vnet"]

  drill-1:
    build:
      context: ./drill
      args:
        cluster_id: 'drillbit'
        hdfs_server: 'hdfs://hdfs:9000'
        quorum: 'server.1=0.0.0.0:2888:3888'

    ports:
      - 8047:8047
    tty: true
    depends_on:
      - "zoo-1"
      - "hdfs"
    networks: ["vnet"]

networks: 
  vnet:
    external: 
      name: vnet      
