version: '3'

services:

  zoo-1:
    build:
      context: ./zookeeper
      ports:
        - 2181:2181
      args:
        quorum: 'server.1=0.0.0.0:2888:3888'
        server_num: '1'

  hdfs:
    build:
      context: ./hadoop
      ports:
        - 8088:8088

  drill-1:
    build:
      context: ./drill
      ports:
        - 8047:8047
      args:
        cluster_id: 'drillbit'
        hdfs_server: 'hdfs://hdfs:9000'
        quorum: 'server.1=0.0.0.0:2888:3888'
      stdin_open: true
      tty: true
      depends_on:
        - "zoo1"
        - "hdfs"
     
