version: '3'

services:

  zoo-1:
    hostname: zoo-1
    restart: always
    image: nickkbright/zoo1:latest
    deploy:
      mode: replicated
      replicas: 2
    networks:
      vnet:
        aliases: 
          - zoo-1
  
  zoo-2:
    hostname: zoo-2
    restart: always
    image: nickkbright/zoo2:latest
    deploy:
      mode: replicated
      replicas: 2
    networks: 
      vnet:
        aliases: 
          - zoo-2
  
  zoo-3:
    hostname: zoo-3
    restart: always
    image: nickkbright/zoo3:latest
    deploy:
      mode: replicated
      replicas: 2
    networks: 
      vnet:
        aliases: 
          - zoo-3
  
  hdfs:
    image: nickkbright/hdfs:latest
    deploy:
      mode: replicated
      replicas: 2
    ports:
        - 8088:8088
    networks: 
      vnet:
        aliases: 
          - hdfs

  drill-1:
    hostname: drill-1
    image: nickkbright/apache-drill:1-14
    deploy:
      mode: replicated
      replicas: 2
    ports:
      - 8047:8047
    depends_on:
      - "zoo-1"
      - "zoo-2"
      - "zoo-3"
      - "hdfs"
    networks: 
      vnet:
        aliases: 
          - drill-1
    healthcheck:
      test: ["/usr/local/bin/restart.sh 1"]
      interval: 50s
      timeout: 3s
      retries: 3

  drill-2:
    hostname: drill-2
    image: nickkbright/apache-drill:1-14
    deploy:
      mode: replicated
      replicas: 2
    depends_on:
      - "zoo-1"
      - "zoo-2"
      - "zoo-3"
      - "hdfs"
    networks: 
      vnet:
        aliases: 
          - drill-2
    healthcheck:
      test: ["/usr/local/bin/restart.sh 2"]
      interval: 50s
      timeout: 3s
      retries: 3

  
  drill-3:
    hostname: drill-3
    image: nickkbright/apache-drill:1-14
    deploy:
      mode: replicated
      replicas: 2
    depends_on:
      - "zoo-1"
      - "zoo-2"
      - "zoo-3"
      - "hdfs"
    networks: 
      vnet:
        aliases: 
          - drill-3
    healthcheck:
      test: ["/usr/local/bin/restart.sh 3"]
      interval: 50s
      timeout: 3s
      retries: 3

  
  drill-4:
    hostname: drill-4
    image: nickkbright/apache-drill:1-14
    deploy:
      mode: replicated
      replicas: 2
    depends_on:
      - "zoo-1"
      - "zoo-2"
      - "zoo-3"
      - "hdfs"
    networks: 
      vnet:
        aliases: 
          - drill-4
    healthcheck:
      test: ["/usr/local/bin/restart.sh 4"]
      interval: 50s
      timeout: 3s
      retries: 3

networks: 
  vnet:
    driver: bridge    
