version: '3'

services:

  zoo-1:
    hostname: zoo-1
    restart: always
    build:
      context: ./zookeeper
      args:
        quorum: 'server.1=0.0.0.0:2888:3888\nserver.2=zoo-2:2888:3888\nserver.3=zoo-3:2888:3888'
        server_num: '1'
    networks:
      vnet:
        aliases: 
          - zoo-1
  
  zoo-2:
    hostname: zoo-2
    restart: always
    build:
      context: ./zookeeper
      args:
        quorum: 'server.1=zoo-1:2888:3888\nserver.2=0.0.0.0:2888:3888\nserver.3=zoo-3:2888:3888'
        server_num: '2'
    networks: 
      vnet:
        aliases: 
          - zoo-2
  
  zoo-3:
    hostname: zoo-3
    restart: always
    build:
      context: ./zookeeper
      args:
        quorum: 'server.1=zoo-1:2888:3888\nserver.2=zoo-2:2888:3888\nserver.3=0.0.0.0:2888:3888'
        server_num: '3'
    networks: 
      vnet:
        aliases: 
          - zoo-3
  
  hdfs:
    build:
      context: ./hadoop
    ports:
        - 8088:8088
    networks: 
      vnet:
        aliases: 
          - hdfs

  drill-1:
    hostname: drill-1
    build:
      context: ./drill
      args:
        cluster_id: 'drillbit'
        hdfs_server: 'hdfs://hdfs:9000'
        quorum: 'zoo-1:2181,zoo-2:2181,zoo-3:2181'
    ports:
      - 8047:8047
    depends_on:
      - "zoo-1"
      - "zoo-2"
      - "zoo-3"
      - "hdfs"
    networks: 
      vnet:
        aliases: 
          - drill-1
    healthcheck:
      test: ["CMD", "/usr/local/bin/restart.sh", "1"]
      interval: 50s
      timeout: 3s
      retries: 3

  drill-2:
    hostname: drill-2
    build:
      context: ./drill
      args:
        cluster_id: 'drillbit'
        hdfs_server: 'hdfs://hdfs:9000'
        quorum: 'zoo-1:2181,zoo-2:2181,zoo-3:2181'
    ports:
      - 8047:8047
    depends_on:
      - "zoo-1"
      - "zoo-2"
      - "zoo-3"
      - "hdfs"
    networks: 
      vnet:
        aliases: 
          - drill-2
    healthcheck:
      test: ["CMD", "/usr/local/bin/restart.sh", "2"]
      interval: 50s
      timeout: 3s
      retries: 3

  drill-3:
    hostname: drill-3
    build:
      context: ./drill
      args:
        cluster_id: 'drillbit'
        hdfs_server: 'hdfs://hdfs:9000'
        quorum: 'zoo-1:2181,zoo-2:2181,zoo-3:2181'
    ports:
      - 8047:8047
    depends_on:
      - "zoo-1"
      - "zoo-2"
      - "zoo-3"
      - "hdfs"
    networks: 
      vnet:
        aliases: 
          - drill-3
    healthcheck:
      test: ["CMD", "/usr/local/bin/restart.sh", "3"]
      interval: 50s
      timeout: 3s
      retries: 3

  drill-4:
    hostname: drill-4
    build:
      context: ./drill
      args:
        cluster_id: 'drillbit'
        hdfs_server: 'hdfs://hdfs:9000'
        quorum: 'zoo-1:2181,zoo-2:2181,zoo-3:2181'
    ports:
      - 8047:8047
    depends_on:
      - "zoo-1"
      - "zoo-2"
      - "zoo-3"
      - "hdfs"
    networks: 
      vnet:
        aliases: 
          - drill-4
    healthcheck:
      test: ["CMD", "/usr/local/bin/restart.sh", "4"]
      interval: 50s
      timeout: 3s
      retries: 3


networks: 
  vnet:
    driver: bridge    

  